### PR TITLE
Add architecture diagram

### PR DESCRIPTION
**Pull request by shawnbot**
I'm actually not sure where this should live, but I'm putting it in `/assets` for now. What do you think, @ultrasaurus? Or does it go in a separate branch and we just reference that branch from the README?

### CODE REVIEW

**Comment by ultrasaurus** [comment]
I usually make a directory called /doc and reference it from the README.  No need to actuallly serve it up as an asset when this is deployed as a website :)

**Comment by hollyallen** [comment]
@shawnbot can you make the change suggested by @ultrasaurus to your pull request, then I can merge and make the required change to the README

**Comment by abisker** [comment]
Hey @ultrasaurus is this ready to merge?

**Comment by hollyallen** [comment]
That looks great! Can you also move the image file from /assets into maybe a new directory called /doc?

**Comment by ultrasaurus** [comment]
we're moving toward having a docs directory that would also have /screenshots that might be someday displayed on a dashboard, so I implemented idea from @hollyallen -- made plural since that's what @melodykramer picked for Open Opps

**Pull request merged**
