### PR TITLE
Adds 'under investigation' UI

### PR DESCRIPTION
**Pull request by meiqimichelle**
This adds UI for the 'under investigation' flags on individual school pages and on search results. The larger task is tracked in #175.

While I was there, I also took care of visual bug #334.

## Results page, desktop:
screen shot 2015-08-10 at 9 58 52 am

## Results page, mobile:
screen shot 2015-08-10 at 10 00 36 am

## Individual school, desktop
screen shot 2015-08-10 at 10 06 55 am

## Individual school, mobile
screen shot 2015-08-10 at 10 05 37 am

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@shawnbot This is ready to go, but of course at the moment ends up on *all* the search results and individual school pages. Still perhaps worth merging now to have it ready when you're ready to add that hook to the API.

Also, the tooltips for the new additions aren't 'arrowing' right. This is a good test page to make sure several types of tips work -- those on new lines and those at the end of their associated text.

**Comment by saintsoup52** [comment]
Not that anyone asked... but I think this visual of what we call a caution flag is pretty neat... good job.

**Comment by meiqimichelle** [comment]
@jjoteal See compliment above :)

**Comment by meiqimichelle** [comment]
Also, for the record, this implementation has a 1-px-width bug in Firefox -- the 'ribbon tale' looks either 1px too short or 1px too tall, depending on the height settings, but never right on. Given our tight timeline to beta, I decided that this was not likely worth fixing right now.

**Comment by LisaGee** [comment]
Go Jess and Michelle!

**Pull request merged**
