### PR TITLE
Adding tests for the individual school page.

### PR DESCRIPTION
**Pull request by DavidEBest**
These tests cover the functionality of the `PICC Individual School Page Test Template` and the 'individual school page' tests from `Test plan`.

### CODE REVIEW

**Comment by DavidEBest** [comment]
D'oh. I think the successful running of these tests depends on some of the config tweaks in `search-tests`.

**Comment by DavidEBest** [comment]
@shawnbot Fixed!

**Comment by hollyallen** [comment]
Is this ready to merge?

**Comment by DavidEBest** [comment]
From my perspective, yes. @shawnbot?

**Pull request merged**
