### PR TITLE
Fixed an issue where changing pages from the bottom paginator would not scroll back to the top of the result list

### PR DESCRIPTION
**Pull request by mark-adams**
I was checking out the new college choice site yesterday on my Nexus 5 and noticed a strange issue. It looks like pagination currently doesn't return you to the top of the results list which seems like an awkward experience for users on mobile. I've fixed the issue by using the existing `scrollIntoView()` method to scroll the form back to the top whenever results from another page are loaded.

Steps to reproduce:
1) Open the site on a mobile device and perform a search
2) Scroll the bottom of the results list and change pages by clicking on a page number

Expected: The new result items are loaded and the browser is scrolled back to the top of the result list
Actual: The new result items are loaded and the browser position remains the same

### CODE REVIEW

**Comment by mark-adams** [comment]
No problem! Please let me know if I need to make any changes!

Keep up the great work!

**Comment by mark-adams** [comment]
Just noticed that this was still out here and rebased it against the current dev.

**Comment by ultrasaurus** [comment]
this seems like a nice usability improvement and it's a small code change.

@shawnbot can you review and merge or comment?

**Comment by mark-adams** [comment]
No problem! You guys do great work! Keep it up! :tada:

**Pull request merged**
