### PR TITLE
Functional test fixes

### PR DESCRIPTION
**Pull request by shawnbot**
This PR will:

- [x] Eliminate false positives for failed tests #367 
- [x] Switch test runner and Selenium driver from Nightwatch to WebDriverIO
- [x] Get tests working on Circle CI (Travis was having issues with Ruby and Node)
- [x] Turn off the Travis integration.
- [x] Remove stale tests that always fail.
- [x] Update `test/README.md` with updated testing instructions

### CODE REVIEW

**Comment by meiqimichelle** [comment]
# FAILING FTW !

screenshot 2015-09-10 14 09 24

**Comment by afeld** [comment]
> Travis is failing somewhere inside the initial `nvm install` step

This seems worth reaching out to Travis support about.

> We do have the option of caching the node_modules directory, but that becomes a pain if our dependencies change and we forget to clear Travis's cache.

I don't think you would need to clear the cache (other than to get rid of unused modules)...I would guess that it will still run `npm install` and update any that don't meet your version restrictions.

**Comment by hollyallen** [comment]
This ticket is marked as in progress, but isn't assigned. I think that @shawnbot and @yozlet were working on it a few weeks ago though. Status?

**Comment by yozlet** [comment]
Yep, @shawnbot & I have been tinkering with this occasionally, and now have a first fully-automated test using a browser through Sauce Labs against the Jekyll build, running on CircleCI. This one test doesn't do very much (checks the page title) but it's a start!

@shawnbot, what's left to do in the checklist a the top?

**Comment by yozlet** [comment]
Note: The reason there's a red X against all recent commits is that Travis is still trying to run tests that don't work well on Travis, which is why we now run them on Circle instead. So, as part of merging this branch, we need to remove the Travis integration from the repo.

**Comment by yozlet** [comment]
All boxes ticked! However, this branch is a total mess. We're going to branch off this and then squash all the commits into something far smaller.

**Pull request merged**
